version: "3"

services:
  api:
    build: ./api
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mongodb

  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

